### ISSUE TITLE
Deprecation warning for `PermissionTarget` with resource being moved to another provider

### ISSUE THREAD

**Issue by zbuchheit** [pulumi/pulumi-artifactory#864]
### Describe what happened

The resource PermissionTarget has been deprecated in favor for a new resource, [Permission](https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/permission), but the new resource has been moved to the `jfrog/platform` provider which we do not currently bridge. This poses a problem for users who leverage this resource today, but have no path to workaround the issue.

### Sample program

Use the PermissionTarget resource and receive the following warning

```
 warning: urn:pulumi:dev::artifactory::artifactory:index/permissionTarget:PermissionTarget{...redacted} verification warning: This resource has been deprecated in favor of "platform_permission" (https://registry.terraform.io/providers/jfrog/platform/latest/docs/resources/permission) resource.
```

### Affected Resource(s)

PermissionTarget

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hi @zbuchheit. I think the quickest way to get past this is to [dynamically bridge](https://www.pulumi.com/blog/) `jfrog/platform`:

```console
$ pulumi package add jfrog/platform
```

**Comment by zbuchheit** [comment]
The user is using pulumi yaml which I believe is a limitation for using dynamically bridge providers at the moment.

**Comment by iwahbe** [comment]
> The user is using yaml which I believe is a limitation for using dynamically bridge providers at the moment.

Ah, yeah. That should be fixed soon, but right now they are not compatable.

**Comment by mjeffryes** [comment]
Is this concern primarily about needing access to the new resource in `jfrog/platform` or about suppressing the warning? 

If the former, we should link the user request to https://github.com/pulumi/pulumi/issues/16802 which would unblock the use of local packages from YAML programs.

**Comment by zbuchheit** [comment]
It is a bit of both. Originally the user just wanted to suppress the warning, but failed to realize the warning is saying that the resource will be removed in the future and replaced by a resource in another package that we don't currently bridge. 

Having YAML support should in theory block the user, but it is unclear if they will be accepting of that workaround because of other potential limitations. I will link the other issue and follow up with the user once it is fixed to see if it will work for them.

**Comment by zbuchheit** [comment]
related question, is there a way to generate/output pulumi-style schema with dynamic providers, and what would be the way to download/pin a specific provider version?

**Comment by mjeffryes** [comment]
You can specify a version to fetch when generating the SDK:

`$ pulumi package add terraform-provider [<registry>/]<author>/<name> [version]`

(https://www.pulumi.com/registry/packages/terraform-provider/installation-configuration/) 

I would recommend checking in the generated SDKs as well. (Not strictly nescessary to pin the provider version, but insulates from any Pulumi codegen change. Alternatively; pining the versions of pulumi and the pulumi-terraform-provider plugin is also sufficient.)

**Comment by mjeffryes** [comment]
I think we should treat this issue as the request to suppress the warning and the https://github.com/pulumi/business-development/issues/181 issue as the request for supporting the provider where this resource is moving.

**Comment by iwahbe** [comment]
> related question, is there a way to generate/output pulumi-style schema with dynamic providers, and what would be the way to download/pin a specific provider version?

Yes:

```console
$ pulumi package get-schema terraform-provider [<registry>/]<author>/<name> [version]
```

This will pipe the generated schema to stdout. You can redirect to a file (with `> schema.json`) as needed.

**Comment by iwahbe** [comment]
We can suppress the warning for the final release of v7, but `PermissionTarget` has been removed in v8 (upstream v12.0.0), which is about ready to release.

**Comment by mjeffryes** [comment]
I'd say we should not bother with the warning then, but will need to stay on our toes for https://github.com/pulumi/business-development/issues/181 in case we can't meet the need with just pulumi-terraform-provider

**Comment by zbuchheit** [comment]
The deprecation warning is disruptive enough that it is clogging up useful logging for the user. Shipping https://github.com/pulumi/pulumi-artifactory/commit/472fab7ee0487ea9f59eb7fb53ad61e5cd30b246 should alleviate that pressure, and give the user some space to prepare for the breaking resource move.
